---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tomcat
  name: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - image: tomcat:9.0
        ports: 
          - containerPort: 8080
            protocol: TCP
        imagePullPolicy: Always
        name: tomcat

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tomcat
  name: tomcat
spec:
  ports:
  - nodePort: 32223
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: tomcat
  type: NodePort